micronaut:
  application:
    name: nossaCasaDoCodigo
datasources:
  default:
    url: jdbc:mariadb://localhost:3307/livraria
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: bruno@zup531
    schema-generate: CREATE_DROP
    dialect: MariaDB103Dialect
jpa.default.properties.hibernate.hbm2ddl.auto: update
